'use strict';
// HANDOFF.md / PROGRESS.md are regenerated from data, every time a packet is
// made or applied. Nobody hand-edits them. This is a direct fix for the
// "agent forgets to update the tracking file" failure mode documented for
// the other Nugget Nihongo project (Crispy / learnings.md): if a human or
// agent has to remember to update a status file, it eventually won't happen.
// Here the status file IS the ledger, rendered.
const fs = require('fs');
const path = require('path');
const { LAYERS, readLedger, openIssues, writeFileAtomic } = require('./store');
const { makeAjv } = require('./schemas');
const { validateStore } = require('./validate-core');
const { loadStore } = require('./store');

function renderProgress(root) {
  const ledger = readLedger(root);
  const lines = [
    '# PROGRESS.md',
    '',
    '_Generated by `tools/lib/handoff.js`. Do not hand-edit — it is rebuilt from `audit/packets.jsonl` on every `packet`/`apply` run._',
    '',
    '| Packet | Type | Layer | By | Applied | Rejected | Missing | When |',
    '|---|---|---|---|---:|---:|---:|---|',
  ];
  for (const e of ledger.slice().reverse().slice(0, 40)) {
    lines.push(`| ${e.packet_id} | ${e.type} | ${e.layer} | ${e.event === 'made' ? '—' : e.by} | ${e.applied ?? '—'} | ${e.rejected ?? '—'} | ${e.missing ?? '—'} | ${e.at} |`);
  }
  if (ledger.length > 40) lines.push('', `_(${ledger.length - 40} older row(s) omitted — full history in \`audit/packets.jsonl\`)_`);
  if (!ledger.length) lines.push('| _(none yet)_ | | | | | | | |');
  return lines.join('\n') + '\n';
}

function renderHandoff(root, pending) {
  const store = loadStore(root);
  const { stats } = validateStore(store, { ajv: makeAjv(root) });
  const issues = openIssues(root);
  const lines = ['# HANDOFF.md', '', '_Generated — do not hand-edit. Regenerated by `tools/make-packet.js` / `tools/apply-packet.js`._', ''];

  if (pending) {
    lines.push(
      `## Next: run packet ${pending.packet_id}`,
      '',
      `- Type: **${pending.type}** on layer **${pending.layer}** — ${pending.ids.length} record(s)`,
      `- Packet file: \`packets/${pending.packet_id}.json\``,
      `- Prompt: use the existing prompt at \`${pending.prompt_ref || '(none set — pass --prompt-ref)'}\` — do not improvise a new one`,
      pending.reviewer_hint ? `- Reviewer note: ${pending.reviewer_hint}` : null,
      '',
      '**Loop:** open the packet JSON → run it with the prompt above (any model) → save the reply as pure JSONL →',
      `\`npm run apply -- --packet packets/${pending.packet_id}.json --output <reply.jsonl> --by <actor, e.g. gemini/2.5-pro>\`.`,
      ''
    );
  } else {
    lines.push('## Next', '', '_No pending packet. Run `npm run packet -- --help` to cut one._', '');
  }

  lines.push('## Store snapshot', '');
  for (const layer of Object.keys(LAYERS)) {
    const s = stats.status[layer];
    lines.push(`- **${layer}**: ${stats.counts[layer]} records — draft ${s.draft}, checked ${s.checked}, verified ${s.verified}`);
  }
  lines.push(
    `- coverage: gloss ${stats.coverage.withGloss}/${stats.coverage.entries} entries, sentences ${stats.coverage.sentences} (${stats.coverage.withSentence}/${stats.coverage.entries} entries)`,
    `- open issues (failed review, not yet fixed): ${issues.size}`,
    ''
  );
  if (issues.size) {
    lines.push('## Open issues', '');
    let n = 0;
    for (const [key, ev] of issues) { if (n++ >= 20) { lines.push(`- … +${issues.size - 20} more (see \`audit/issues.jsonl\`)`); break; } lines.push(`- \`${key}\` [${(ev.codes || []).join(', ')}] ${ev.note || ''} (packet ${ev.packet})`); }
    lines.push('');
  }
  lines.push('## Rules for the next agent', '', '- Follow the packet\'s `output_contract` exactly — JSONL only, listed fields only, no extra ids.', '- Never invent record ids.', '- Use the prompt this packet points to; do not write a new persona/prompt.', '');
  return lines.join('\n');
}

/** Call after any packet lifecycle event. `pending` = the packet still awaiting an apply, or null. */
function refreshHandoffFiles(root, pending) {
  writeFileAtomic(path.join(root, 'PROGRESS.md'), renderProgress(root));
  writeFileAtomic(path.join(root, 'HANDOFF.md'), renderHandoff(root, pending));
}

module.exports = { refreshHandoffFiles, renderProgress, renderHandoff };
